<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TiaV18PublicApiDirectory Condition="'$(TiaV18PublicApiDirectory)' == ''">C:\Program Files\Siemens\Automation\Portal V18\PublicAPI\V18</TiaV18PublicApiDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EngineerPc.Tia.V18.Protocol\EngineerPc.Tia.V18.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Siemens.Engineering">
      <HintPath>$(TiaV18PublicApiDirectory)\Siemens.Engineering.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>