<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EngineerPc.Contracts\EngineerPc.Contracts.csproj" />
    <ProjectReference Include="..\EngineerPc.Engineering.Transactions\EngineerPc.Engineering.Transactions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
